layout grid

cd ~/Laylah/laylah

launch zsh -c "cd hub; just run-proxy"
launch zsh -c "cd hub; just run-configure"
launch zsh -c "cd hub; just run-ingest"
launch zsh -c "cd hub; just run-consume"
launch zsh -c "cd hub; just run-sync"
launch zsh -c "cd hub; just run-notify"
launch zsh -c "cd ui; just install; just web"
