"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
[☭](bold red) [$directory](blue)\
$git_branch$git_state$git_status\
"""

[git_branch]
format = '[\($branch\)]($style)'

[git_status]
format = '[$untracked$modified$staged$deleted$renamed]($style) '
